# Generated by Django 5.0.1 on 2024-01-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Client Name')),
                ('telephone', models.CharField(max_length=12, verbose_name='Client Telephone')),
                ('email', models.EmailField(max_length=254, verbose_name='Client Email')),
                ('postcode', models.CharField(max_length=12, verbose_name='Client Postcode')),
                ('property_type', models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('RESIDENTIAL', 'Residential')], default='COMMERCIAL', max_length=12, verbose_name='Client Property')),
                ('description', models.TextField(verbose_name='Client Description')),
                ('received', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
            },
        ),
    ]
