# Generated by Django 5.0.1 on 2024-01-17 10:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=30, verbose_name='Status')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Last Name')),
                ('telephone', models.CharField(blank=True, max_length=12, verbose_name='Telephone')),
                ('telephone_alt', models.CharField(blank=True, max_length=12, verbose_name='Alternative Telephone')),
                ('email', models.EmailField(blank=True, max_length=30, verbose_name='Email')),
                ('position', models.CharField(blank=True, max_length=30, verbose_name='Position')),
                ('business_name', models.CharField(blank=True, max_length=30, verbose_name='Business Name')),
                ('address_line_1', models.CharField(blank=True, max_length=50, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=50, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='City')),
                ('postcode', models.CharField(blank=True, max_length=12, verbose_name='Postcode')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Job Notes')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Inspections',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Inspection Fee')),
                ('date', models.DateField(verbose_name='Inspection Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Job Notes')),
                ('completed', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=30, verbose_name='Completed(?)')),
                ('paid', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=30, verbose_name='Paid(?)')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_jobs.clients')),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'ordering': ['-date'],
            },
        ),
    ]
